frontend/src/config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import include, path
from django.views import defaults as default_views
from django.views.generic import TemplateView

urlpatterns = [
    path("", TemplateView.as_view(template_name="pages/home.html"), name="home"),
    path("about/", TemplateView.as_view(template_name="pages/about.html"), name="about"),
    # Django Admin, use {% url 'admin:index' %}
    path(settings.ADMIN_URL, admin.site.urls),
    # User management
    path("users/", include("frontend.users.urls", namespace="users")),
    path("accounts/", include("allauth.urls")),
    # Your stuff: custom urls includes go here
    path("macro_us/", include("frontend.macro_us.urls", namespace="macro_us")),
    path("macro_eu/", include("frontend.macro_eu.urls", namespace="macro_eu")),
    path("dbmf/", include("frontend.dbmf.urls", namespace="dbmf")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
if settings.DEBUG:
    # Static file serving when using Gunicorn + Uvicorn for local web socket development
    urlpatterns += staticfiles_urlpatterns()


if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

frontend/src/frontend/dbmf/urls.py
from django.urls import path
from frontend.dbmf import views

app_name = 'dbmf'
urlpatterns = [
    path("", views.DbmfView.as_view(), name='dbmf'),
]

frontend/src/frontend/macro_eu/urls.py
from django.urls import path
from frontend.macro_eu import views

app_name = 'macro_eu'
urlpatterns = [
    path("metrics/", views.MacroEuMetrics.as_view(), name='macro_eu_metrics'),
    path("countries/", views.MacroEuCountries.as_view(), name='macro_eu_countries'),
]

frontend/src/frontend/macro_us/urls.py
from django.urls import path
from frontend.macro_us import views

app_name = 'macro_us'
urlpatterns = [
    path("metrics/", views.MacroUsMetrics.as_view(), name='macro_us_metrics'),
    # path("ism-manu/", views.MacroUsIsmManu.as_view(), name='macro_us_ism_manu'),
    # path("ism-serv/", views.MacroUsIsmServ.as_view(), name='macro_us_ism_serv'),
]

frontend/src/frontend/users/urls.py
from django.urls import path

from frontend.users.views import (
    user_detail_view,
    user_redirect_view,
    user_update_view,
)

app_name = "users"
urlpatterns = [
    path("~redirect/", view=user_redirect_view, name="redirect"),
    path("~update/", view=user_update_view, name="update"),
    path("<str:username>/", view=user_detail_view, name="detail"),
]

frontend/src/frontend/users/models.py
from django.contrib.auth.models import AbstractUser
from django.db.models import CharField
from django.urls import reverse
from django.utils.translation import gettext_lazy as _


class User(AbstractUser):
    """
    Default custom user model for frontend.
    If adding fields that need to be filled at user signup,
    check forms.SignupForm and forms.SocialSignupForms accordingly.
    """

    # First and last name do not cover name patterns around the globe
    name = CharField(_("Name of User"), blank=True, max_length=255)
    first_name = None  # type: ignore
    last_name = None  # type: ignore

    def get_absolute_url(self) -> str:
        """Get URL for user's detail view.

        Returns:
            str: URL for user detail.

        """
        return reverse("users:detail", kwargs={"username": self.username})

frontend/src/frontend/users/forms.py
from allauth.account.forms import SignupForm
from allauth.socialaccount.forms import SignupForm as SocialSignupForm
from django.contrib.auth import forms as admin_forms
from django.contrib.auth import get_user_model
from django.utils.translation import gettext_lazy as _

User = get_user_model()


class UserAdminChangeForm(admin_forms.UserChangeForm):
    class Meta(admin_forms.UserChangeForm.Meta):
        model = User


class UserAdminCreationForm(admin_forms.UserCreationForm):
    """
    Form for User Creation in the Admin Area.
    To change user signup, see UserSignupForm and UserSocialSignupForm.
    """

    class Meta(admin_forms.UserCreationForm.Meta):
        model = User
        error_messages = {
            "username": {"unique": _("This username has already been taken.")},
        }


class UserSignupForm(SignupForm):
    """
    Form that will be rendered on a user sign up section/screen.
    Default fields will be added automatically.
    Check UserSocialSignupForm for accounts created from social.
    """


class UserSocialSignupForm(SocialSignupForm):
    """
    Renders the form when user has signed up using social accounts.
    Default fields will be added automatically.
    See UserSignupForm otherwise.
    """

frontend/src/frontend/dbmf/views.py
from django.db import connection
from django.shortcuts import render
from django.views import View


class DbmfView(View):
    pass

frontend/src/frontend/macro_eu/views.py
import os
import requests
from requests import HTTPError
import pandas as pd
import numpy as np
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render
from django.views import View

# from config.settings.local import STATIC_ROOT, STATIC_URL
from frontend.libs import stylers

LIMIT = int(os.getenv("EU_LIMIT_MONTHS"))


class MacroEuMetrics(LoginRequiredMixin, View):
    """Represents EU countries performance - metrics perspective."""

    API_BASE_URL = os.getenv("API_BASE_URL")

    def get(self, request):
        url = os.path.join(self.API_BASE_URL, "eu/metrics")
        response = requests.get(url, timeout=None)
        try:
            response.raise_for_status()
        except HTTPError:
            return render(
                request,
                "404.html",
                {
                    "exception": (
                        f"Not a single EU metric's table in the database. "
                        f"Try feeding the database using updater service."
                    )
                },
            )

        metrics_metadata = response.json()

        metrics_tables = {}
        for metric_code, meta in metrics_metadata.items():
            metric_all_data_url = os.path.join(
                self.API_BASE_URL,
                "eu/metric",
                metric_code,
            )
            response = requests.get(metric_all_data_url)
            try:
                response.raise_for_status()
            except HTTPError:
                continue

            metric_all_data = response.json()
            data = pd.DataFrame(metric_all_data["data"])[-LIMIT:]
            stats_dict = metric_all_data["statistics"]
            stats = pd.DataFrame(
                stats_dict.values(),
                stats_dict.keys(),
            ).transpose()

            data_with_stats = pd.concat([data, stats]).transpose().fillna(np.nan)
            table = stylers.MetricTableStyler(data_with_stats)
            styled_table = table.style_table_index_with_difference_stats()

            metrics_tables[meta.get("code").title()] = styled_table.to_html()

        context = {"tables": metrics_tables}

        return render(request, "macro_eu/eu_metrics.html", context)


class MacroEuCountries(LoginRequiredMixin, View):
    """Represents EU countries performance - country perspective."""

    API_BASE_URL = os.getenv("API_BASE_URL")

    def get(self, request):
        countries_codes_url = os.path.join(self.API_BASE_URL, "eu/countries")
        response = requests.get(countries_codes_url, timeout=None)
        print(response)
        try:
            response.raise_for_status()
        except HTTPError:
            return render(
                request,
                "404.html",
                {
                    "exception": (
                        f"Not a single EU country's table in the database. "
                        f"Try feeding the datbase using updater service."
                    )
                },
            )

        countries_codes: list[str] = response.json()

        countries_tables = {}
        for country_code in countries_codes:
            country_data_url = os.path.join(
                self.API_BASE_URL,
                "eu/country",
                country_code,
                "data",
            )
            country_stats_url = os.path.join(
                self.API_BASE_URL,
                "eu/country",
                country_code,
                "stats",
            )

            response_data = requests.get(country_data_url)
            try:
                response_data.raise_for_status()
            except HTTPError:
                continue
            country_data = response_data.json()

            response_stats = requests.get(country_stats_url)
            try:
                response_stats.raise_for_status()
            except HTTPError:
                continue
            country_stats = response_stats.json()

            data = pd.DataFrame(country_data)[-LIMIT:]
            stats = pd.DataFrame(country_stats)
            data_with_stats = pd.concat([data, stats]).transpose()
            table = stylers.MetricTableStyler(data_with_stats)
            styled_table = table.style_table_index_with_difference_stats()

            countries_tables[country_code.upper()] = styled_table.to_html()

        context = {"tables": countries_tables}

        return render(request, "macro_eu/eu_countries.html", context)

frontend/src/frontend/macro_us/views.py
import os
import requests
from requests import HTTPError
import pandas as pd
import numpy as np
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render
from django.views import View

# from config.settings.local import STATIC_ROOT, STATIC_URL
from frontend.libs import stylers

LIMIT = int(os.getenv("US_LIMIT_MONTHS"))


class MacroUsMetrics(LoginRequiredMixin, View):
    # imgs_dir = os.path.join(STATIC_ROOT, "img_us")
    API_BASE_URL = os.getenv("API_BASE_URL")

    def get(self, request):
        url = os.path.join(self.API_BASE_URL, "us/metrics")
        response = requests.get(url)
        try:
            response.raise_for_status()
        except HTTPError:
            return render(
                request,
                "404.html",
                {
                    "exception": (
                        f"Not a single US metric's table in the database. "
                        f"Try feeding the database using updater service "
                        f"(if you have got relevant API key/keys)."
                    )
                },
            )

        metrics_metadata = response.json()

        metrics_tables = {}
        for metric_code, meta in metrics_metadata.items():
            metric_all_data_url = os.path.join(
                self.API_BASE_URL,
                "us/metric",
                metric_code,
            )
            response_metric = requests.get(metric_all_data_url)
            try:
                response_metric.raise_for_status()
            except HTTPError:
                continue

            metric_all_data = response_metric.json()
            data = pd.DataFrame(metric_all_data["data"])[-LIMIT:]
            stats_dict = metric_all_data["statistics"]
            stats = pd.DataFrame(
                stats_dict.values(),
                stats_dict.keys(),
            ).transpose()

            data_with_stats = pd.concat([data, stats]).transpose().fillna(np.nan)

            table = stylers.MetricTableStyler(data_with_stats)

            if meta["data"] == "index" and meta["stats"] == "difference":
                styled_table = table.style_table_index_with_difference_stats()
            elif meta["data"] == "index" and meta["stats"] == "change":
                styled_table = table.style_table_index_with_change_stats()
            elif meta["data"] == "change" and meta["stats"] == "difference":
                styled_table = table.style_table_change_with_difference_stats()

            metrics_tables[meta.get("name")] = styled_table.to_html()

        context = {"tables": metrics_tables}

        return render(request, "macro_us/us_metrics.html", context)

frontend/src/frontend/users/views.py
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.urls import reverse
from django.utils.translation import gettext_lazy as _
from django.views.generic import DetailView, RedirectView, UpdateView

User = get_user_model()


class UserDetailView(LoginRequiredMixin, DetailView):
    model = User
    slug_field = "username"
    slug_url_kwarg = "username"


user_detail_view = UserDetailView.as_view()


class UserUpdateView(LoginRequiredMixin, SuccessMessageMixin, UpdateView):
    model = User
    fields = ["name"]
    success_message = _("Information successfully updated")

    def get_success_url(self):
        assert self.request.user.is_authenticated  # for mypy to know that the user is authenticated
        return self.request.user.get_absolute_url()

    def get_object(self):
        return self.request.user


user_update_view = UserUpdateView.as_view()


class UserRedirectView(LoginRequiredMixin, RedirectView):
    permanent = False

    def get_redirect_url(self):
        # return reverse("users:detail", kwargs={"username": self.request.user.username})
        return reverse("home")

user_redirect_view = UserRedirectView.as_view()

frontend/src/frontend/templates/403_csrf.html
{% extends "base.html" %}

{% block title %}Forbidden (403){% endblock title %}
{% block content %}
  <h1>Forbidden (403)</h1>
  <p>
    {% if exception %}
      {{ exception }}
    {% else %}
      You're not allowed to access this page.
    {% endif %}
  </p>
{% endblock content %}

frontend/src/frontend/templates/base.html
{% load static i18n %}<!DOCTYPE html>
{% get_current_language as LANGUAGE_CODE %}
<html lang="{{ LANGUAGE_CODE }}">
<head>
  <meta charset="utf-8" />
  <meta http-equiv="x-ua-compatible" content="ie=edge" />

  <title>
    {% block title %}
      rs-data
    {% endblock title %}
  </title>

  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <meta name="description"
        content="Frontend for rs-data service." />
  <meta name="author"
        content="Rafal Sukiennik" />
  <link rel="icon" href="{% static 'images/favicons/favicon.ico' %}" />

  {% block css %}
    <!-- Latest compiled and minified Bootstrap CSS -->
    <link rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap/5.1.3/css/bootstrap.min.css"
          integrity="sha512-GQGU0fMMi238uA+a/bdWJfpUGKUkBdgfFdgBm72SUQ6BeyWjoY/ton0tEjH+OSH9iP4Dfh+7HM0I9f5eR0L/4w=="
          crossorigin="anonymous"
          referrerpolicy="no-referrer" />
  <!-- Your stuff: Third-party CSS libraries go here -->
  <!-- This file stores project-specific CSS -->
  <link href="{% static 'css/project.css' %}" rel="stylesheet" />
  {% endblock css %}

  <!-- Le javascript
      ================================================== -->
  {# Placed at the top of the document so pages load faster with defer #}
  {% block javascript %}
  <!-- Bootstrap JS -->
  <script defer
          src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap/5.1.3/js/bootstrap.min.js"
          integrity="sha512-OvBgP9A2JBgiRad/mM36mkzXSXaJE9BEIENnVEmeZdITvwT09xnxLtT4twkCa8m/loMbPHsvPl0T8lRGVBwjlQ=="
          crossorigin="anonymous"
          referrerpolicy="no-referrer"></script>
  <!-- Your stuff: Third-party javascript libraries go here -->

  <!-- place project specific Javascript in this file -->

  <script defer src="{% static 'js/project.js' %}"></script>
  {% endblock javascript %}
</head>
<body>
  <header class="site-header">
    <nav class="navbar fixed-top navbar-expand-md navbar-light bg-light">
      <div class="container-fluid">
        <button class="navbar-toggler navbar-toggler-right"
                type="button"
                data-bs-toggle="collapse"
                data-bs-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent"
                aria-expanded="false"
                aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>

        <a class="navbar-brand" href="{% url 'home' %}">rs-data</a>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav me-auto">
            <li class="nav-item active">
              <a class="nav-link" href="{% url 'home' %}">Home <span class="visually-hidden">(current)</span></a>
            </li>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                Macro
              </a>
              <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                <!-- <li><a class="dropdown-item" href="{% url 'home' %}">US Overview</a></li> -->
                <li><a class="dropdown-item" href="{% url 'macro_us:macro_us_metrics' %}">US Metrics</a></li>
                <li><hr class="dropdown-divider"></li>
                <li><a class="dropdown-item" href="{% url 'macro_eu:macro_eu_metrics' %}">EU Metrics</a></li>
                <li><a class="dropdown-item" href="{% url 'macro_eu:macro_eu_countries' %}">EU Countries</a></li>
                <li><hr class="dropdown-divider"></li>
              </ul>
            </li>
            <!-- <li class="nav-item">
              <a class="nav-link" href="{% url 'dbmf:dbmf' %}">DBMF</a>
            </li> -->
            <li class="nav-item">
              <a class="nav-link" href="{% url 'about' %}">About</a>
            </li>
          </ul>

          <span class="navbar-nav">
            {% if request.user.is_authenticated %}
              <li class="nav-item">
                <a class="nav-link"
                  href="{% url 'users:detail' request.user.username %}">{% translate "My Profile" %}</a>
              </li>
              <li class="nav-item">
                {# URL provided by django-allauth/account/urls.py #}
                <a class="nav-link" href="{% url 'account_logout' %}">{% translate "Sign Out" %}</a>
              </li>
            {% else %}
              {% if ACCOUNT_ALLOW_REGISTRATION %}
                <li class="nav-item">
                  {# URL provided by django-allauth/account/urls.py #}
                  <a id="sign-up-link" class="nav-link" href="{% url 'account_signup' %}">{% translate "Sign Up" %}</a>
                </li>
              {% endif %}
              <li class="nav-item">
                {# URL provided by django-allauth/account/urls.py #}
                <a id="log-in-link" class="nav-link" href="{% url 'account_login' %}">{% translate "Sign In" %}</a>
              </li>
            {% endif %}
          </span>
        </div>
      </div>
    </nav>
  </header>

  <div class="container mt-5 pt-5 pb-5">
    {% if messages %}
      {% for message in messages %}
        <div class="alert alert-dismissible {% if message.tags %}alert-{{ message.tags }}{% endif %}">
          {{ message }}
          <button type="button"
                  class="btn-close"
                  data-bs-dismiss="alert"
                  aria-label="Close"></button>
        </div>
      {% endfor %}
    {% endif %}

    {% block content %}
      <p>Use this document as a way to quick start any new project.</p>
    {% endblock content %}
  </div>

  <!-- /container -->
  {% block modal %}
  {% endblock modal %}

  {% block inline_javascript %}
    {% comment %}
    Script tags with only code, no src (defer by default). To run
    with a "defer" so that you run inline code:
    <script>
      window.addEventListener('DOMContentLoaded', () => {
        /* Run whatever you want */
      });
    </script>
    {% endcomment %}
  {% endblock inline_javascript %}
</body>
</html>